#1. What was the toaster project? What did Thomas Thwaites attempt to do? Was he successful and what is the significance of this example in the context of complexity and development? 
  In the Toaster Project, Thomas Thwaites attempted to rebuild the simplest toaster he could find from scratch. Building the toaster from scratch was extremely complicated and took nine months. Once completed and plugged in the toaster burst into flames in mere seconds. Thwaites called this a partial success. This project demonstrated there is complexity and many working parts and systems to create a product. This relates to complexity and development as a whole because develeopment comes from emergence of a whole system, not an individual product or firm. 

#2.  According to Barder, how successful have economic models been at describing and predicting growth over the past 50 years?  How did he use the Harrod-Domar model, the Solow model, the Washington consensus and the Ajoakuta Steel works to illustrate his point (reference at least two of the above). 
  The last 50 years have been the most most successful in human development. However, economist have not necessarily been very accurate in their models or predicitions of growth. In the Harrod-Domar growth model there was an emphasis on more capital being needed. Where a certain amount and capital would increase the output. Robert Solow had the Neoclassical growth method which pointed at technical change as a main component of development. Barder points out that in these and other models there is exeplained pieces and just a bunch of numbers. No models can truely explain why some countries see growth and others dont. What usually is missing is not some simple ingredient.

#3.  Who was Steve Jones? What did he do at uni-lever? Was he successful?  Specifically what did he do in order to make an evolutionary jump forward?  How significant were his results?
  Steve Jones is an evolutionary biologist who worked at a soap making factory. He tried to make a nozzle to ease the process used in soap making. He made about a hundred random combinitations of generations of nozzles and tested them. When he found one that worked it was not one that would have ever been designed or thought of. His design was leaps and bounds better than the origninal. This is significant because showed how adaptive change brings great improvement. Its all about adaptation and evolution in order to find out what works best. 
  
#4.  Who was Haile Sellasie?  What is the significance of Kapuscinski’s book, The Emporer?  According to Barder, how did Ethiopia exemplify the suppression of emergent systemic change?  How do you think Sen would have described this suppression? Do you agree?
 Haile Sellaise was an emperor of Ethopia. Kauscinski's book was about Sellaise's last days as emperor. By the rulers suppressing the people's efforts, they were suppressing the possibilty of systemic change. This change would threathen the ruler's position of power. Barder then points to the value of democracy. I think Sen would have described this suppression as unfreedom. When there is unfreedom it is harder for development to occur. Without the citizens having freedom of speech and freedom to political expression, they are unable to develop as a whole which is what these dictators and oligarchies wanted so they could remain in power. I agree with Sen and Barder that without democracy there is a supression of possible systemic change. 
  
